version: '3'

services:
  db:
    image: mongo
    container_name: crate-db
    restart: always
    expose:
      - 27017
    ports:
      - 27018:27017
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    networks:
      - crate
    volumes:
      - dbdata:/data/db
  client:
    container_name: crate-client
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - 3002:3002
    networks:
      - crate
  server:
    container_name: crate-server
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - crate

networks:
  crate:
    driver: bridge

volumes:
  dbdata:
